
/***********************************************
    Conversation -- Fields
    int conversationId: Used to group collections of messages together
    int userId: Users ID who initiated the conversation
    int recieverId: Users ID who was the reciever when conversation was created

    Conversation -- Methods
    findByUserIdAndRecieverId: Will match passed in users to a specific conversation and return its ID

    Message -- Fields
    int messageId: Generic id autogenerated at creation
    int conversationId: Used to group messages together
    int originUserId
    String message
    Date timeStamp: timestamp of when the object got created

    Message -- Methods
    findAllByConversationId: Finds all matching messages and returns a list

 ***********************************************/

package com.SE370.Cougar.Roomie.model.message;